.PHONY: init watch

init:
	databricks bundle generate dashboard --existing-path '/Workspace/Users/{{user_name}}/{{.dashboard_path}}.lvdash.json'

edit:
	databricks bundle generate dashboard --existing-path '/Workspace/Users/{{user_name}}/{{.dashboard_path}}.lvdash.json' --watch

